/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nova_android_opengl_NationOpenGL */

#ifndef _Included_nova_android_opengl_NationOpenGL
#define _Included_nova_android_opengl_NationOpenGL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nova_android_opengl_NationOpenGL
 * Method:    nativeSurfaceCreate
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_nova_android_opengl_NationOpenGL_nativeSurfaceCreate
  (JNIEnv *, jobject, jobject);

/*
 * Class:     nova_android_opengl_NationOpenGL
 * Method:    nativeSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_nova_android_opengl_NationOpenGL_nativeSurfaceChanged
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     nova_android_opengl_NationOpenGL
 * Method:    nativeSurfaceDestroyed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nova_android_opengl_NationOpenGL_nativeSurfaceDestroyed
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
